php artisan make:seeder loginSeeder
php artisan make:seeder emailSeeder
php artisan make:seeder ipSeeder
php artisan make:seeder latitudeSeeder
php artisan make:seeder longitudeSeeder
php artisan make:seeder userSeeder
php artisan make:seeder estabelecimentoSeeder
php artisan make:seeder estab_cepSeeder
php artisan make:seeder telefoneSeeder
php artisan make:seeder tipo_servicoSeeder
php artisan make:seeder veiculoSeeder
php artisan make:seeder estab_estadoSeeder
php artisan make:seeder estab_cidadeSeeder
php artisan make:seeder estab_bairroSeeder
php artisan make:seeder estab_enderSeeder
php artisan make:seeder represent_contatoSeeder
php artisan make:seeder empresaSeeder
